services:
  # Servidor Backend de Medusa (Gratuito)
  - type: web
    name: babygoo-backend
    env: node
    plan: free
    region: ohio
    buildCommand: "unset NODE_OPTIONS && cd .medusa/server && npm ci --omit=dev"
    startCommand: "cd .medusa/server && npx medusa start --port 10000 --host 0.0.0.0"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "22.18.0"
      - key: HOST
        value: 0.0.0.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=460
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: STORE_CORS
        value: "https://tudominio-storefront.com"
      - key: ADMIN_CORS
        value: "https://tudominio-admin.com"
      - key: AUTH_CORS
        value: "https://tudominio-admin.com,https://tudominio-storefront.com"
      - key: STRIPE_API_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
